server:
  port: 9023

spring:
  application:
    name:consumer-feign
logging:
  level:
    cn.study.service: DEBUG
eureka: 
  client: 
    register-with-eureka: false #客户端不注册到eureka，只是进行服务的调用
    service-url: 
      defaultZone: http://eureka-9013.com:9013/eureka,http://eureka-9012.com:9012/eureka,http://eureka-9011.com:9011/eureka
  instance:
    instance-id: consumer-feign  # 在信息列表时显示主机名称
    prefer-ip-address: true
feign:
  compression:
    request:
      mime-types:       # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩