quartz:
  enabled: true
server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_quartz
    username: yourname
    password: yourpassword
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
logging:
  level:
    cn.study.service: DEBUG

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-9013.com:9013/eureka,http://eureka-9012.com:9012/eureka,http://eureka-9011.com:9011/eureka
  instance:
    instance-id: quarzt  # 在信息列表时显示主机名称
    prefer-ip-address: true