server:
  port: 9002
#mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  #type-aliases-package: cn.study.vo            # 定义所有操作类的别名所在包
  #mapper-locations:                                     # 所有的mapper映射文件
  #- classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name:dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:sqlserver://192.168.0.180:1400/DatabaseName=SAS_LY           # 数据库连接地址
    username: sa                                  # 数据库用户名
    password: Sas123456!     # 数据库连接密码
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
eureka:
  enable-self-preservation: true # 设置为false表示关闭保护模式
  eviction-interval-timer-in-ms: 60000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-9013.com:9013/eureka,http://eureka-9012.com:9012/eureka,http://eureka-9011.com:9011/eureka
  instance:
    instance-id: dept1  # 在信息列表时显示主机名称
    prefer-ip-address: true
    
info:
  app.name: cloud-dept
  company.name: www.study.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$