
server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-9013.com:9013/eureka,http://eureka-9012.com:9012/eureka,http://eureka-9011.com:9011/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: gateway-9501.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: study-microcloud
  company.name: www.study.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

spring:
  application:
    name: zuul-gateway